### ISSUE TITLE
欢迎大家加入微信群！！！！！！！！！！！！！

### ISSUE THREAD

**Issue by ZTjack** [1token-trade/onetoken#2]
由于群内人数已达100人以上，只可以邀请加入群聊，请各位在评论中留下您的微信号，我个人加您后，拉您进群

**Comment by cedricporter** [comment]
wechat:  Oxl234

**Comment by ZTjack** [comment]
或者将您的微信号，发至onetoken.trade@outlook.com，我每日会查收

**Comment by oldcodeoberyn** [comment]
请拉我吧，我用的是mac，但发现连不上啊
lexlee327

**Comment by ZTjack** [comment]
欢迎大家通过扫描官网下方的“微信交流群”，加入我们的官方微信群，有问题可以直接在群里问，效率最高~

**Comment by alpharothschild** [comment]
你的微信号是

**Comment by ZTjack** [comment]
@alpharothschild 您加一下微信群吧，里面同事更多，能解决更多问题。（群里我叫jack）

**Comment by tangyouze** [comment]
扫描二维码加群
![image](https://user-images.githubusercontent.com/815306/45592681-c542d000-b9a6-11e8-9cbb-19eb8c84f742.png)
